//
// Created by artsiom on 13.06.20.
//

#ifndef WEBSOCKETTEST_MESSAGETYPECONST_H
#define WEBSOCKETTEST_MESSAGETYPECONST_H

#define MESSAGE_TYPE_SHOW_UP "SHOW_UP"
#define MESSAGE_TYPE_REGISTER "REGISTER"
#define MESSAGE_TYPE_START_SESSION "START_SESSION"
#define MESSAGE_TYPE_STOP_SESSION "STOP_SESSION"

#endif //WEBSOCKETTEST_MESSAGETYPECONST_H
