//
// Created by artsiom on 13.06.20.
//

#ifndef WEBSOCKETTEST_MESSAGETYPECONST_H
#define WEBSOCKETTEST_MESSAGETYPECONST_H

#define MESSAGE_TYPE_SHOW_UP "SHOW_UP"
#define MESSAGE_TYPE_SHOW_UP_ACK "SHOW_UP_ACK"

#define MESSAGE_TYPE_REGISTRATION "REGISTRATION"

#define MESSAGE_TYPE_START_SESSION "START_SESSION"
#define MESSAGE_TYPE_START_SESSION_ACK "START_SESSION_ACK"

#define MESSAGE_TYPE_PING "PING"
#define MESSAGE_TYPE_PING_ACK "PING_ACK"

#define MESSAGE_TYPE_START_ACTION "START_ACTION"
#define MESSAGE_TYPE_START_ACTION_ACK "START_ACTION_ACK"
#define MESSAGE_TYPE_ACTION_FINISHED "ACTION_FINISHED"

#define MESSAGE_TYPE_STOP_SESSION "STOP_SESSION"

#endif //WEBSOCKETTEST_MESSAGETYPECONST_H
